// automatically generated by the FlatBuffers compiler, do not modify

package cfg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
type Conf struct {
	_tab flatbuffers.Table
}

func GetRootAsConf(buf []byte, offset flatbuffers.UOffsetT) *Conf {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Conf{}
	x.Init(buf, n + offset)
	return x
}

func (rcv *Conf) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Conf) HealthbeatInterval() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Conf) HealthbeatPushPeriod() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Conf) SaveInterval() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func ConfStart(builder *flatbuffers.Builder) { builder.StartObject(3) }
func ConfAddHealthbeatInterval(builder *flatbuffers.Builder, HealthbeatInterval int64) { builder.PrependInt64Slot(0, HealthbeatInterval, 0) }
func ConfAddHealthbeatPushPeriod(builder *flatbuffers.Builder, HealthbeatPushPeriod int64) { builder.PrependInt64Slot(1, HealthbeatPushPeriod, 0) }
func ConfAddSaveInterval(builder *flatbuffers.Builder, SaveInterval int64) { builder.PrependInt64Slot(2, SaveInterval, 0) }
func ConfEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
