// automatically generated by the FlatBuffers compiler, do not modify

package cfg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)
type NodeInf struct {
	_tab flatbuffers.Table
}

func GetRootAsNodeInf(buf []byte, offset flatbuffers.UOffsetT) *NodeInf {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeInf{}
	x.Init(buf, n + offset)
	return x
}

func (rcv *NodeInf) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeInf) ID() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *NodeInf) Hostname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeInf) Region() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeInf) Zone() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NodeInf) DataCenter() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NodeInfStart(builder *flatbuffers.Builder) { builder.StartObject(5) }
func NodeInfAddID(builder *flatbuffers.Builder, ID uint32) { builder.PrependUint32Slot(0, ID, 0) }
func NodeInfAddHostname(builder *flatbuffers.Builder, Hostname flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Hostname), 0) }
func NodeInfAddRegion(builder *flatbuffers.Builder, Region flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(Region), 0) }
func NodeInfAddZone(builder *flatbuffers.Builder, Zone flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(Zone), 0) }
func NodeInfAddDataCenter(builder *flatbuffers.Builder, DataCenter flatbuffers.UOffsetT) { builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(DataCenter), 0) }
func NodeInfEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT { return builder.EndObject() }
