// Code generated by "stringer -type=OutputType"; DO NOT EDIT

package output

import "fmt"

const _OutputType_name = "UnsuportedFileInfluxDB"

var _OutputType_index = [...]uint8{0, 10, 14, 22}

func (i OutputType) String() string {
	if i < 0 || i >= OutputType(len(_OutputType_index)-1) {
		return fmt.Sprintf("OutputType(%d)", i)
	}
	return _OutputType_name[_OutputType_index[i]:_OutputType_index[i+1]]
}
